apiVersion: v1
kind: Namespace
metadata:
  name: #{kubernetes_namespace}#
  
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
   app: nodejs
spec:
   type: LoadBalancer
   ports:
    - port: 8081
   selector:
      app: nodejs
      
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nodejs-deployment
  annotations:
   kubernetes.io/change-cause: "Deploy with new image tag #{Build.BuildId}#"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: #{docker_image}#:#{Build.BuildId}#
        ports: 
         - containerPort: 8081
      imagePullSecrets:  
              - name: #{dockerregistry_credentials}#
